---
- name: Install docker dependencies
  become: yes
  apt:
    pkg:
      - python3-pip
    update_cache: yes
- name: Install docker as dependency for docker_image
  pip:
    name: docker
    state: present
- name: Create docker-registry directory
  file:
    path: /docker-mounts/docker-registry
    state: directory
- name: Install docker registry
  community.docker.docker_container:
    name: docker-registry
    image: registry:2
    recreate: yes
    restart_policy: always
    published_ports:
      - 5000:5000
    mounts:
      - source: /docker-mounts/docker-registry
        target: /var/lib/registry
        type: bind
    network_mode: bridge
  