---
- name: Create docker-registry directory
  file:
    path: "{{ docker_folder }}/docker-registry"
    state: directory
- name: Install docker registry
  community.docker.docker_container:
    name: docker-registry
    image: registry:2
    recreate: yes
    restart_policy: always
    published_ports:
      - 5000:5000
    mounts:
      - source: "{{ docker_folder }}/docker-registry"
        target: /var/lib/registry
        type: bind
    network_mode: bridge
  